
on:
  push:
    branches:
      - dev
      - qa
      - prod
      - main

jobs:
  terraform:
    name: 'Terraform-dev'
    runs-on: ubuntu-latest


    defaults:
      run:
        shell: bash

    steps:
      # Checkout the repository to the GitHub Actions runner
      - name: Checkout
        uses: actions/checkout@v2

      # Install the latest version of Terraform CLI and configure the Terraform CLI configuration file with a Terraform Cloud user API token
     # - name: Setup Terraform
      #  uses: hashicorp/setup-terraform@v1
       #with:
        #  cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

      - name: if qa, terraform init, validate, plan, apply
       # if: github.ref == 'refs/heads/qa' && github.event_name == 'push'
        run: |
          #cd ppb
          export AWS_ACCESS_KEY_ID=AKIA2DPJPWLRSTLULZQ2
          export AWS_SECRET_ACCESS_KEY=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
          terraform init
          #terraform workspace new dev
          #terraform validate -no-color
          #terraform plan -no-color
          #terraform apply -auto-approve
          terraform destroy
        #env:
         # TYRELL_ENVIRONMENT: "qa"
